Feature: Save mirror
marcioaffonso/opentok-mirror pull request #2
Opened 2017-06-12 15:32 UTC by maikthomas

So far I've added the front-end logic for the client-mirror - I figured let's get this one right first then replicate for the server.

I've added the back-end api paths and dummy responses. Need to add integration with Redis and actual save/retrieve functionality.

2017-06-12 15:36 UTC, maikthomas commented on src/js/App.js
> +        </Switch>
If you don't use `<Switch>` then you can't use `exact` in the redirect, which leads to things things `/client-mirror/` redirecting to `/client-mirror/client-mirror` and so and and so forth for eternity :|
https://github.com/ReactTraining/react-router/blob/master/packages/react-router/docs/api/Switch.md

2017-06-12 15:36 UTC, maikthomas commented on src/js/components/clientMirror/ActionBar.js
> +import FaFloppyO from 'react-icons/lib/fa/floppy-o';
Just a quick solution, perhaps we want to use something else?

2017-06-12 15:36 UTC, maikthomas commented on src/js/components/clientMirror/ActionBar.js
> +            style={{ display: this.props.options.isRunning ? 'inline-block' : 'none' }}
I think we need to sort out the style. This works fine on a big screen but on my laptop screen it goes over onto two lines

2017-06-12 15:36 UTC, maikthomas commented on src/js/pages/ClientMirror.js
> +export default withRouter(ClientMirror);
these `withRouter` part are needed to do the redirect. 
https://reacttraining.com/react-router/web/api/withRouter

2017-06-13 08:13 UTC, marcioaffonso commented on src/js/App.js
> +        </Switch>
Great!

2017-06-13 08:13 UTC, marcioaffonso commented on src/js/components/clientMirror/ActionBar.js
> +import FaFloppyO from 'react-icons/lib/fa/floppy-o';
Yes, I think we should Bootstrap icons as we are already using them: https://www.w3schools.com/icons/bootstrap_icons_glyphicons.asp

I can change that.

2017-06-13 08:14 UTC, marcioaffonso commented on src/js/pages/ClientMirror.js
> +export default withRouter(ClientMirror);
Great!

2017-06-13 08:18 UTC, marcioaffonso requested changes

2017-06-13 08:18 UTC, marcioaffonso commented on src/js/App.js
> +const NotFound = () => (
Does this work just by assigning this constant?

2017-06-13 08:18 UTC, marcioaffonso commented on src/js/components/clientMirror/ActionBar.js
> +            style={{ display: this.props.options.isRunning ? 'inline-block' : 'none' }}
I can change that too, don't worry.

2017-06-13 08:18 UTC, marcioaffonso commented on src/js/pages/ClientMirror.js
>      this.state = {
I think this code is duplicated. Before the constructor could be removed.

2017-06-13 09:14 UTC, maikthomas commented on src/js/pages/ClientMirror.js
>      this.state = {
I'll investigate this.

2017-06-13 09:15 UTC, maikthomas commented on src/js/components/clientMirror/ActionBar.js
> +import FaFloppyO from 'react-icons/lib/fa/floppy-o';
Great, do you want to just push it onto this branch or change it after?

2017-06-13 09:16 UTC, maikthomas commented on src/js/App.js
> +const NotFound = () => (
No. This is a mistake

2017-06-13 09:35 UTC, maikthomas commented on src/js/pages/ClientMirror.js
>      this.state = {
@marcioaffonso Here it says `constructor` comes under Mounting: "Mounting
These methods are called when an instance of a component is being created and inserted into the DOM"
Whilst `componentWIllReceiveProps` comes under Updating: "An update can be caused by changes to props or state. These methods are called when a component is being re-rendered:"
and below "React doesn't call componentWillReceiveProps with initial props during mounting"

So I think we need both. Source:
https://facebook.github.io/react/docs/react-component.html#the-component-lifecycle

2017-06-13 09:44 UTC, marcioaffonso approved these changes

2017-06-13 09:45 UTC, merged